[Mozilla Branding Removal] Removing branding
mozilla/dialog pull request #57
Opened 2024-07-09 14:27 UTC by markusTraber

- For Github-Actions (.github/workflows/dialog.yml) I've changed the registry to "Hubs-Foundation", even though this account seemingly does not exist (yet?)
- Codeowners: Just referenced the org here, without referencing any team
- As for Habitat (habitat/plan.sh): I changed origin and maintainer. But it does have dependencies to Mozilla packages. Is Habitat even still relevant for us?

2024-07-23 05:51 UTC, Exairnous requested changes
Thanks!  This is looking good.
I've left a couple inline comments and I'll check in with the rest of the governance team about the docker registry.

As for the Habitat stuff, I don't know, it seems to be included in a couple repositories, but I'm not sure if it's still being used or not.  I'll ask some of the former Hubs team members about this in the Discord.

2024-07-23 05:51 UTC, Exairnous commented on .github/workflows/dialog.yml
> +    uses: Hubs-Foudation/hubs-ops/.github/workflows/turkeyGitops.yml@master
Hubs-Foudation is missing an "n".

2024-07-23 05:51 UTC, Exairnous commented on CODEOWNERS
> +.github/workflows   @Hubs-Foundation
Apparently GitHub doesn't like this, so just use the Operations team for now.  We should probably revisit stuff like this later on a larger scale and decide how we want to handle it.
```suggestion
.github/workflows   @Hubs-Foundation/operations 
```

2024-07-23 08:45 UTC, markusTraber commented on .github/workflows/dialog.yml
> +    uses: Hubs-Foudation/hubs-ops/.github/workflows/turkeyGitops.yml@master
Oh 😅 Thank you. I changed it.

2026-02-24 19:34 UTC, DougReeder commented
Sorry we didn't get to this sooner. Closed in favor of https://github.com/Hubs-Foundation/dialog/pull/60

2026-02-24 19:34 UTC, closed without merging